version: '3.2'
services:
  bot:
    build:
      context: .
      cache_from:
      - python:3.8-alpine
      # labels: []
      # tags: []
    # image: ~
    # container_name: ~
    restart: always
    pull_policy: build
    volumes:
    - type: bind
      source: ./config.yml
      target: /app/config.yml
      read_only: true
